# General settings
data_paths:
  raw: data/raw/raw.csv
  interim: data/interim/interim.csv
  processed: data/processed/processed.csv

artifact_paths:
  model: artifacts/models/model.pkl

api_settings:
  host: localhost
  port: 5000